### ISSUE TITLE
Update from latest grammarly wordiness list

### ISSUE THREAD

**Issue by franklin-ross** [duereg/too-wordy#6]
The wordiness list has some notable absences, like `off of`, which are on the grammarly list mentioned in the readme. Is that intentional, has the list not been updated recently?

https://grammarist.com/wordiness/

**Comment by duereg** [comment]
Updated! This has gone out in `0.3.1`. Thanks for the heads up.

**Comment by franklin-ross** [comment]
No worries! Thanks for getting that out ⭐
